use_frameworks!

platform :ios, '9.0'

target 'DSlider_Example' do
  pod 'DSlider', :path => '../'

  target 'DSlider_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
